### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cr0vy** [cr0vy/custom_gentoo_build#1]
1. Current / now
- [ ] LiveCD:
  - [ ] Buildable stage1
    - [ ] Use an external file for USE flags
  - [ ] Buildable stage2
  - [ ] Buildable stage3
- [ ] Installer
  - [x] Basic partition setup
  - [ ] User creation
  - [ ] Locale setup
  - [ ] Ebuild

2. Future
- [ ] Better name than custome_gentoo_build
- [ ] Python script wrapper for emerge / portage
